apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: launchpad-builder
  annotations:
    description: This template creates a Build Configuration using an S2I builder.
    tags: instant-app
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: nodejs-cache-cute-name
  spec: {}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi8/nodejs-14:latest'
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: nodejs-cache-cute-name
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-cache-cute-name:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime:latest
        incremental: true
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  spec:
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    type: ClusterIP
    selector:
      project: nodejs-cache-cute-name
      provider: nodeshift
  metadata:
    name: nodejs-cache-cute-name
    labels:
      provider: nodeshift
      expose: 'true'
      project: nodejs-cache-cute-name
      version: 4.0.0
      'app.openshift.io/runtime': 'nodejs'
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: nodejs-cache-cute-name
    labels:
      app: nodejs-cache-cute-name
      provider: nodeshift
      project: nodejs-cache-cute-name
      version: 4.0.0
      'app.openshift.io/runtime': 'nodejs'
  spec:
    template:
      spec:
        containers:
          - readinessProbe:
              httpGet:
                path: /ready
                port: 8080
                scheme: HTTP
            livenessProbe:
              httpGet:
                path: /live
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 30
            image: nodejs-cache-cute-name
            name: nodejs-cache-cute-name
            securityContext:
              privileged: false
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
      metadata:
        labels:
          app: nodejs-cache-cute-name
          project: nodejs-cache-cute-name
          provider: nodeshift
          version: 4.0.0
    replicas: 1
    selector:
      app: nodejs-cache-cute-name
      project: nodejs-cache-cute-name
      provider: nodeshift
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - nodejs-cache-cute-name
          from:
            kind: ImageStreamTag
            name: 'nodejs-cache-cute-name:latest'
- apiVersion: route.openshift.io/v1
  kind: Route
  spec:
    to:
      kind: Service
      name: nodejs-cache-cute-name
    port:
      targetPort: 8080
  metadata:
    name: nodejs-cache-cute-name
    labels:
      provider: nodeshift
      project: nodejs-cache-cute-name
      version: 4.0.0
      'app.openshift.io/runtime': 'nodejs'
